server:
  port: 9091

spring:
  thymeleaf:
    cache: false

  datasource:
    username: root
    password: 123456
    #    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/tz_data?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    neo4j:
      uri: bolt://localhost
      username: neo4j
      password: 123456


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  redis:
    host: 127.0.0.1
    port: 6379
  mybatis:
    mapper-locations: classpath:mapper/*.xml        #扫描所有xml文件
    type-aliases-package: com.example.server.entity
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl     #打印日志